databases:
  - name: coffee-db
    plan: free
    databaseName: coffee_shop # The actual name of the database
    user: db_user       # The username for the database

services:
  - type: web
    name: coffee-shop-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: coffee-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: coffee-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: coffee-db
          property: password
      - key: APP_JWTSECRET
        value: p2s5v8y/B?E(H+MbQeThWmZq4t7w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSg